# Deployment for nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-green
  namespace: hbg-app
  labels:
    app: app-nginx
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-nginx
      version: green
  template:
    metadata:
      labels:
        app: app-nginx
        version: green
    spec:
      containers:
      - name: app-nginx
        image: nginx:1.23  # Use a specific version rather than latest
        ports:
        - name: app-port
          containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/green
          readOnly: true
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
        - name: html-volume
          configMap:
            name: html-content-green
        - name: nginx-config-volume
          configMap:
            name: nginx-config

---
# Service to expose the nginx pods
apiVersion: v1
kind: Service
metadata:
  name: app-svc-green
  namespace: hbg-app
  labels:
    app: app-nginx
    version: green
spec:
  type: NodePort
  selector:
    app: app-nginx
    version: green
  ports:
  - name: svc-port
    port: 80
    targetPort: app-port
    nodePort: 30082

---

# ConfigMap for nginx HTML content
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content-green
  namespace: hbg-app
  labels:
    app: app-nginx
    version: green
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>HelloBagHub</title></head>
    <body>
      <h1>Welcome to HelloBagHub!</h1>
      <h2>You are accessing to GreenEnv</h2>
    </body>
    </html>
  health.html: |
    { "status": "ok" }

---

# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: hbg-app
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;

        location / {
        root /usr/share/nginx/html;  # default app directory
        index index.html;
      }

      # Serve Green App on /green URL
      location /green/ {
          root /usr/share/nginx/html;  # Green app directory
          index green/index.html;
      }
    }
