
# Deployment for nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-blue
  namespace: hbg-app
  labels:
    app: app-nginx
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-nginx
      version: blue
  template:
    metadata:
      labels:
        app: app-nginx
        version: blue
    spec:
      containers:
      - name: app-nginx
        image: nginx:latest
        ports:
        - name: app-port
          containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
        - name: html-volume
          configMap:
            name: html-content-blue
---
# Service to expose the nginx pods
apiVersion: v1
kind: Service
metadata:
  name: app-svc-blue
  namespace: hbg-app
  labels:
    app: app-nginx
    version: blue
spec:
  type: NodePort
  selector:
    app: app-nginx
    version: blue
  ports:
  - name: svc-port
    port: 80
    targetPort: app-port
    nodePort: 30081

---  # ✅ This line separates the Service from the ConfigMap

# ConfigMap for nginx
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-content-blue
  namespace: hbg-app
  labels:
    app: app-nginx
    version: blue
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>HelloBagHub</title></head>
    <body>
      <h1>Welcome to HelloBagHub!</h1>
      <h2>You are accessing to ProdEnv</h2>
    </body>
    </html>

  health.html: |
    { "status": "ok" }

